

"""
STACK:
LAST IN FIRST OUT : LIKE A STACK OF PANCAKES

INSERTION ORDER!!!!

PUSH ADDS NEWEST ELEMENT TO THE END
POP REMOVES NEWEST ELEMENT AT THE END

0(1) -> ACCESS NEWEST ELEMENT
0(N) -> ACCESS THE OLDEST ELEMENT

QUEUE:
FIRST IN LAST OUT : LIKE A LINE OF PEOPLE ORDING FOOD

INSERTION ORDER!!!!

ENQUEUE: ADDING A NEW ELEMENT TO THE END 
DEQUEUE: POPING OLDEST ELEMENT IN THE FRONT 

0(N) -> ACCESS THE NEWEST ELEMENT
0(1) -> ACCESS THE OLDEST ELEMENT



"""